### ISSUE TITLE
Repair UP Doubt

### ISSUE THREAD

**Issue by mmconnectdev** [OLayemii/flutter-ui-kits#6]
Hi there, 
Before the question, let me tell you that i love your job here. Really good UI's. 
Now the question: 

On the Repair Service UI's how does the routs work ? 
Im interested in making the 1 st buttons to redirect to diferent pages but they just go to the same one all the time. Tried to learn about Dynamic Routes but the ones i see are easly edited and this one inst (So far). Any tip ? 

Edit 1: 

On request_service_flow.dart if i comment // the //HomePageTwo(nextPage: nextPage, prevPage: prevPage), when i click on any button on page 1 it goes to page 3. Still how the hell do i redirect this buttons to diferent pages each ?

**Comment by olayemii** [comment]
@nunomonteiro123 Thanks, I dont totally get the issue, What I have done is to increment a page state value and display a different content based on the state.

Are you trying to route to a different page?

**Comment by mmconnectdev** [comment]
I can see the pages have a "Key" value, and i want to redirect them to a new page that matches that key value. But where do i define the page "key" on the new page ? and where do i have to add the page route ? 

Edit #1: Already know what to do. Sry for the time.
