### ISSUE TITLE
Bug when creating the laundry app. Child for ScreenUtilInit is deprecated.

### ISSUE THREAD

**Issue by awoyele** [OLayemii/flutter-ui-kits#7]
Hi When installing in flutter sdk >= 2.2.*
There is an error showing Child component is not a parameter
<img width="1369" alt="Screen Shot 2021-06-20 at 4 48 38 PM" src="https://user-images.githubusercontent.com/16243076/122689330-6067d480-d1e7-11eb-834e-516c0f49ece3.png">

**Comment by olayemii** [comment]
Cool @awoyele, I'll try to upgrade all codes here to be compatible with sdk 2.x over the week.

**Comment by awoyele** [comment]
If you need any help, let me know the scope & I'll make changes

**Comment by olayemii** [comment]
@awoyele upgrades made yesterday.. All works well 👍
